### ISSUE TITLE
Craft 4 Support

### ISSUE THREAD

**Issue by javangriff** [sgroupdesign/craft-site-module#3]
With some of our recent sites potentially requiring upgrading to Craft 4, it would be awesome if we could update this module to support Craft 4. I'm not sure if this is as simple as updating the required craft version from `"craftcms/cms": "^3.7.0"` to `"craftcms/cms": "^4.0.0"` or if there are other more significant changes required.

**Comment by engram-design** [comment]
Requires some testing, but scheduling in the move to Craft 4 in July!

**Comment by javangriff** [comment]
Excuse me Mr @engram-design, any update on when you will be able to update this for Craft 4. I'm more than happy to jump in and make the updates, but it would probably be quicker for you to do them.

**Comment by engram-design** [comment]
Done! [2.0.1](https://github.com/sgroupdesign/craft-site-module/releases/tag/2.0.1)
